#fundamentals of tensors using tf

More specifically,
1. Introduction to tensors
2. Getting info from tensors
3. Modifying tensors
4. Tensors & numpy
5. Using @tf.function(speed python functions)
6. Using gpu/tpu
7. practice


In [1]:
#import tf
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
#creating tensors with tf.constant()
scalar = tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [3]:
#check the number of dims of a tensor
scalar.ndim

0

In [4]:
#create a vector
vector = tf.constant([32,32])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([32, 32], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
#create a matrix
mat = tf.constant([
                  [1,2],
                  [3,4]
                   ])
mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [7]:
mat.ndim

2

In [8]:
#create another mat
mat1 = tf.constant([
                  [10., 3.1],
                  [1.3, 5.],
                  [4.5, 10.1], 
                  ], dtype=tf.float16)
mat1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10. ,  3.1],
       [ 1.3,  5. ],
       [ 4.5, 10.1]], dtype=float16)>

In [9]:
mat1.ndim

2

In [10]:
#lets create tensor

tensor1 = tf.constant([[[1,2,3],
                        [3,4,4]],
                       [[6,6,3],
                        [8,7,1]],
                       [[6,4,21],
                        [12,12,6]]])
tensor1

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  4]],

       [[ 6,  6,  3],
        [ 8,  7,  1]],

       [[ 6,  4, 21],
        [12, 12,  6]]], dtype=int32)>

In [11]:
tensor1.ndim

3

* Scalar - a single real number
* Vector - a real number with direction
* Matrix - a 2-dim array of real numbers
* Tensor - an n-dim array of numbers

###creating tensors with tf.Variable

In [12]:
#create the same tensor as above tensor1 with tf.Variable()
mutable_tensor = tf.Variable([10,7])
immutable_tensor = tf.constant([10,7])
mutable_tensor, immutable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
mutable_tensor[0] = 3

TypeError: ignored

In [ ]:
mutable_tensor[0].assign(3)
mutable_tensor

In [ ]:
immutable_tensor[0] = 3

In [ ]:
immutable_tensor[0].assign(3)

###creating random tensors
Random tensors are tensors of some arbitray size and contain random numbers.

In [ ]:
#creating random tensors
rand_tensors = tf.random.Generator.from_seed(70)
rand_tensors = rand_tensors.normal(shape=(5,5))
rand_tensor_copy = rand_tensors

In [ ]:
rand_tensor_copy

In [ ]:
rand_tensors2 = tf.random.Generator.from_seed(70)
rand_tensors2 = rand_tensors2.normal(shape=(5,5))
rand_tensors2

In [ ]:
rand_tensors2, rand_tensors == rand_tensor_copy

##shuffling tensors

In [ ]:
##shuffling tensors(valuable when we want to shuffle data)
unshuffled = tf.constant([[10,7],
                          [3,4],
                          [2,5]])
unshuffled.ndim

In [ ]:
shuffled = tf.random.shuffle(unshuffled)

In [ ]:
shuffled

# HW Read thru below link
https://www.tensorflow.org/api_docs/python/tf/random/set_seed

###Turn Numpy arrays into tensors
tensors can be run faster on GPU as compared to np arrays

In [ ]:
import numpy as np
np_arr = np.arange(1, 49, dtype=np.float32)
np_arr

In [ ]:
conv_tensor = tf.constant(np_arr, shape=(8,2,3))

In [ ]:
np_arr, conv_tensor

In [ ]:
conv_tensor_rehsaped = tf.reshape(conv_tensor, (48,1))

In [ ]:
conv_tensor_rehsaped

###Getting info from tensor
* shape -> len of the number of elements of each of the dimensions of a tensor. tensor.shape
* rank -> number of tensor dimensions. rank(scalar)= 0, rank(vec)= 1, rank(mat) = 2, rank(n-tensor) = n. also can be got by tensor.ndim
* axis(dim) -> particular dim of a tensor. tensor[0], ...tensor[:,1]
* size -> total number of items in the tensor. tf.size(tensor)


In [ ]:
tensor_obj = tf.ones(shape=[2 , 3, 5, 8])
tensor_obj.shape , tf.rank(tensor_obj) , tensor_obj.ndim, tf.size(tensor_obj)

In [ ]:
tensor_obj[0]

In [ ]:
 #Get attributes of tensor
 print("Datatype of every element:", tensor_obj.dtype)
 print("Number of dimensions(rank):", tensor_obj.ndim)
 print("Shape of tensor:", tensor_obj.shape)
 print("Elements along the zero-axis:", tensor_obj.shape[0])
 print("Elements along the last-axis:", tensor_obj.shape[-1])
 print("Total number of elements in our tensors:", tf.size(tensor_obj))
 print("Total number of elements in our tensors:", tf.size(tensor_obj).numpy())

##Indexing Tensors
Tensors can be indexed just like python

In [ ]:
#get the first 2 elements of each dim
tensor_obj[:2 , :2 , :2 , :2]

In [ ]:
#Get the first element from each dim from each index except for the final one
tensor_obj[:1, :1, :, :1]

In [14]:
#create a rank2 tensor (2 dims)
tensor_obj2  = tf.ones((4,4))

In [15]:
tensor_obj2

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [16]:
tf.rank(tensor_obj2), tensor_obj2.shape ,  tensor_obj2.ndim 

(<tf.Tensor: shape=(), dtype=int32, numpy=2>, TensorShape([4, 4]), 2)

In [17]:
tensor_obj2[:, -1]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

In [18]:
#add new dim to tensor
# tensor_obj2.ndim
t3 = tensor_obj2[:,:,tf.newaxis]
t3

<tf.Tensor: shape=(4, 4, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]], dtype=float32)>

In [19]:
#expand tensors tf.expand_dims() alternative to tf.newaxis
t0 = tf.constant([[2,3],
                  [4,9]])
#tf.expand_dims(t0, axis=-0) #shape (1,2,2)
tf.expand_dims(t0, axis=0) #shape (1,2,2)


<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 3],
        [4, 9]]], dtype=int32)>

In [20]:
temp1 = tf.expand_dims(t0, axis=-0)
temp2 = tf.expand_dims(t0, axis=0)
temp1 == temp2

<tf.Tensor: shape=(1, 2, 2), dtype=bool, numpy=
array([[[ True,  True],
        [ True,  True]]])>

##manipulating tensors
**basic ops**
+,-,*/

In [21]:
t4 = tf.constant([[15,22],
                 [18,4]])
t4 + 15

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 37],
       [33, 19]], dtype=int32)>

In [22]:
t4 * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 44],
       [36,  8]], dtype=int32)>

In [23]:
t4 * 3.14

TypeError: ignored

In [ ]:
t4 - 5

In [24]:
t4 /3

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5.        , 7.33333333],
       [6.        , 1.33333333]])>

In [25]:
#tf builtin funcs for +,- etc.
tf.multiply(t4, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 44],
       [36,  8]], dtype=int32)>

In [26]:
tf.multiply(t4, 3.14)

TypeError: ignored

###MatMal

In [27]:
t5 = tf.constant([[1,2],
                  [3,4]])

In [28]:
tf.matmul(t5, t5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [29]:
t5 * t5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [30]:
tf.multiply(t5, t5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [31]:
#matmul in python
t5 @ t5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [32]:
t5.shape

TensorShape([2, 2])

In [33]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [34]:
tf.multiply(X,Y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 16],
       [27, 40],
       [55, 72]], dtype=int32)>

In [35]:
tf.matmul(X,Y)

InvalidArgumentError: ignored

In [ ]:
#reshape Y tensor
Y = tf.reshape(Y, shape=(2,3))

In [ ]:
Y

In [ ]:
tf.matmul(X, Y)

In [36]:
 tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

###MatMul can be also be called as dot product

1.   tf.matmul()
2.   tf.tensordot()

In [37]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [38]:
tf.tensordot(X,Y, axes=0)

<tf.Tensor: shape=(3, 2, 3, 2), dtype=int32, numpy=
array([[[[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[14, 16],
         [18, 20],
         [22, 24]]],


       [[[21, 24],
         [27, 30],
         [33, 36]],

        [[28, 32],
         [36, 40],
         [44, 48]]],


       [[[35, 40],
         [45, 50],
         [55, 60]],

        [[42, 48],
         [54, 60],
         [66, 72]]]], dtype=int32)>

In [39]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

###Changing the datatype of tensor

In [40]:
t6 = tf.constant([[3.13, 9.88]])
t6.dtype

tf.float32

In [41]:
t7 = tf.constant([1, 2])
t7.dtype

tf.int32

In [42]:
t8 = tf.cast(t6,tf.int32)
t8, t8.dtype, t6, t6.dtype

(<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[3, 9]], dtype=int32)>,
 tf.int32,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[3.13, 9.88]], dtype=float32)>,
 tf.float32)



---

[Mixed precision in tensorflow](https://www.tensorflow.org/guide/mixed_precision)

In [43]:
t9 = tf.constant([3.12345678987612444, 0.8257426528357478235])

In [44]:
t9

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.1234567 , 0.82574266], dtype=float32)>

In [45]:
t9 = tf.cast(t9, dtype=tf.float16)

In [46]:
t9

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3.123 , 0.8257], dtype=float16)>

###Aggregating Tensors

In [47]:
#Get the absolute values
t10 = tf.constant([-127, -97])
tf.abs(t10)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([127,  97], dtype=int32)>

###Let's go thru below forms of aggregations


*   Get the min
*   Get the max
*   Get the mean of the tensor
*   Get the sum of a tensor



In [48]:
t11 = tf.constant([[15,25],
                   [33,7]])
t11

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 25],
       [33,  7]], dtype=int32)>

In [49]:
aggr1 = tf.reduce_min(t11, axis=-1)
aggr2 = tf.reduce_max(t11, axis=-1)
aggr3 = tf.reduce_mean(t11, axis=-1)
aggr4 = tf.reduce_sum(t11, axis=-1)

aggr1, aggr2, aggr3 , aggr4

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([15,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([25, 33], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 20], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([40, 40], dtype=int32)>)

In [50]:
import numpy as np
rand_tensor = tf.constant(np.random.randint(0,100, size=50))
rand_tensor, rand_tensor.ndim, tf.size(rand_tensor.numpy())

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([13, 52, 57, 49, 85, 49, 98, 87, 96, 43, 92, 13, 54, 76, 57, 94, 43,
        77, 79, 33, 10, 93, 97, 15, 49, 89, 65,  9, 45, 45, 28, 61, 73,  3,
        27, 61, 95, 63, 41, 12, 55, 57, 27, 31, 98, 43, 96, 75, 73, 48])>,
 1,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [51]:
np_arr = np.random.randint(0,100, size=50)
np_arr

array([ 6,  4, 83, 79, 59, 48, 80, 59, 97, 82, 99, 28, 78, 18, 55, 20, 56,
       74, 58, 85,  6, 95, 24, 30, 45, 47, 77, 83, 96, 19, 75, 86, 26,  7,
       71, 49, 44, 95, 16, 24, 13, 98, 46, 11, 18, 16, 24, 43,  5, 87])

In [52]:
len(rand_tensor)
# tf.reduce_mean(rand_tensor)
rand_tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([13, 52, 57, 49, 85, 49, 98, 87, 96, 43, 92, 13, 54, 76, 57, 94, 43,
       77, 79, 33, 10, 93, 97, 15, 49, 89, 65,  9, 45, 45, 28, 61, 73,  3,
       27, 61, 95, 63, 41, 12, 55, 57, 27, 31, 98, 43, 96, 75, 73, 48])>

In [53]:
mean = tf.reduce_mean(rand_tensor)
mean

<tf.Tensor: shape=(), dtype=int64, numpy=56>

In [54]:
#To get variance tensorflow_probability api method2
import tensorflow_probability as tfp
variance = tfp.stats.variance(rand_tensor)
variance

<tf.Tensor: shape=(), dtype=int64, numpy=773>

In [55]:
#get variance method1 
var = tf.math.reduce_variance(tf.cast(rand_tensor, dtype=tf.float32))
var

<tf.Tensor: shape=(), dtype=float32, numpy=773.5556>

In [56]:
#get stddev
stddev = tf.math.reduce_std(tf.cast(rand_tensor, dtype=tf.float32))
stddev

<tf.Tensor: shape=(), dtype=float32, numpy=27.812868>

In [57]:
##Find positional max and min in a tensor
tf.random.set_seed(42)
t12 = tf.random.uniform(shape=[50])
t12

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [58]:
pos_max, pos_min = tf.argmax(t12, axis=0) , tf.argmin(t12)
pos_max, pos_min

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>)

In [59]:
t12[pos_max] , t12[pos_min]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

###Squeezing a tensor(remove all single dimensions)

In [60]:
#create a rand tensor
tf.random.set_seed(42)
t15 = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
t15

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [61]:
tf.squeeze(t15) ## removes all single dimensions 

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One-hot encoding tensors

In [62]:
#create a list of indices
ll = [0, 1, 2] # RGB
tf.one_hot(ll, depth=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [63]:
#custom values for one-hot
tf.one_hot(ll, depth=3, on_value="color", off_value="nocolor")

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'color', b'nocolor', b'nocolor'],
       [b'nocolor', b'color', b'nocolor'],
       [b'nocolor', b'nocolor', b'color']], dtype=object)>

###Squaring, log, sqrt

In [64]:
#again a new tensor
t16 = tf.range(1, 20)

In [65]:
tf.square(t16), tf.sqrt(tf.cast(t16, dtype=tf.float32))

(<tf.Tensor: shape=(19,), dtype=int32, numpy=
 array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
        196, 225, 256, 289, 324, 361], dtype=int32)>,
 <tf.Tensor: shape=(19,), dtype=float32, numpy=
 array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
        2.4494896 , 2.6457512 , 2.8284268 , 2.9999998 , 3.1622777 ,
        3.3166244 , 3.4641016 , 3.6055508 , 3.7416573 , 3.8729832 ,
        3.9999998 , 4.1231055 , 4.2426405 , 4.358899  ], dtype=float32)>)

In [66]:
tf.math.log(tf.cast(t16, dtype=tf.float32))

<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246, 2.3025851, 2.3978953, 2.4849067,
       2.5649493, 2.6390574, 2.7080503, 2.7725887, 2.8332133, 2.8903718,
       2.944439 ], dtype=float32)>

###Tensors and Numpy

In [67]:
#creating tensor from numpy
t17 = tf.constant(np.array([1,5,7]))
t17

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 5, 7])>

In [68]:
#convert tensors using numpy methods //method1
np.array(t17), type(np.array(t17))

(array([1, 5, 7]), numpy.ndarray)

In [69]:
#convert tensors using numpy methods //method2
t17.numpy() , type(t17.numpy())

(array([1, 5, 7]), numpy.ndarray)

In [70]:
#default types of numpy and tf
np_arr = tf.constant(np.array([12.1, 5.1]))
tf_tensor = tf.constant([12.1, 5.1])

np_arr.dtype , tf_tensor.dtype

(tf.float64, tf.float32)

...### 00 TensorFlow Fundamentals 
Exercises
1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9....

In [85]:
#1
K = tf.constant([15])
V = tf.constant([10.1,2.0])
M = tf.constant([[1, 2],
                 [3, 4]])
T = tf.constant(np.random.randint(-128, 127, (32,32,3)))

In [88]:
#2
def attr_tensor(tensor_obj):
  print("shape:", tensor_obj.shape)
  print("rank:", tensor_obj.ndim)
  print("size:", tf.size(tensor_obj))
  print("datatype:", tensor_obj.dtype)
  print(100*"-")

In [89]:
attr_tensor(K) , attr_tensor(V) , attr_tensor(M) , attr_tensor(T)

shape: (1,)
rank: 1
size: tf.Tensor(1, shape=(), dtype=int32)
datatype: <dtype: 'int32'>
----------------------------------------------------------------------------------------------------
shape: (2,)
rank: 1
size: tf.Tensor(2, shape=(), dtype=int32)
datatype: <dtype: 'float32'>
----------------------------------------------------------------------------------------------------
shape: (2, 2)
rank: 2
size: tf.Tensor(4, shape=(), dtype=int32)
datatype: <dtype: 'int32'>
----------------------------------------------------------------------------------------------------
shape: (32, 32, 3)
rank: 3
size: tf.Tensor(3072, shape=(), dtype=int32)
datatype: <dtype: 'int64'>
----------------------------------------------------------------------------------------------------


(None, None, None, None)

In [94]:
#3
tf.random.Generator.from_seed(50)
rand_T1 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
rand_T2 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)

In [95]:
rand_T1, rand_T2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.14241445, 0.40161622, 0.33360183, ..., 0.467453  , 0.4010433 ,
         0.77402675],
        [0.68600106, 0.36842024, 0.838217  , ..., 0.5757059 , 0.321252  ,
         0.4654348 ],
        [0.51995134, 0.3815695 , 0.59582543, ..., 0.09222043, 0.6600671 ,
         0.00907719],
        [0.11020112, 0.18113029, 0.16872919, ..., 0.05145729, 0.21334374,
         0.12166667],
        [0.90618634, 0.7663641 , 0.9128959 , ..., 0.90221953, 0.00464523,
         0.03899753]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.2046014 , 0.82478166, 0.81674874, ..., 0.73888934, 0.8124145 ,
         0.7620115 ],
        [0.17481506, 0.63864744, 0.24706995, ..., 0.67034936, 0.8716053 ,
         0.61141956],
        [0.34407902, 0.42842925, 0.6522441 , ..., 0.9399564 , 0.7259021 ,
         0.23393202],
        [0.5378308 , 0.51275206, 0.9158604 , ..., 0.05066681, 0.77546406,
         0.8794466 ],
        [0.30548

In [96]:
#4
tf.multiply(rand_T1, rand_T2)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.0291382 , 0.3312457 , 0.27246886, ..., 0.34539604, 0.3258134 ,
        0.5898173 ],
       [0.11992332, 0.23529065, 0.20709825, ..., 0.38592407, 0.28000492,
        0.28457594],
       [0.17890435, 0.16347553, 0.38862363, ..., 0.08668318, 0.47914407,
        0.00212345],
       [0.05926956, 0.09287493, 0.15453239, ..., 0.00260718, 0.1654404 ,
        0.10699935],
       [0.27682763, 0.4670001 , 0.3643562 , ..., 0.42928943, 0.00253699,
        0.03342057]], dtype=float32)>

In [101]:
#5
tf.matmul(rand_T1, rand_T2, transpose_a=True)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0.66406304, 1.3870456 , 1.0875493 , ..., 1.4905809 , 1.6714267 ,
        1.5230997 ],
       [0.609398  , 1.2898868 , 1.1396838 , ..., 1.2762036 , 1.4833881 ,
        1.4366192 ],
       [0.7894245 , 1.7085515 , 1.3870792 , ..., 1.8113614 , 2.0635502 ,
        1.836826  ],
       ...,
       [0.53130585, 1.368901  , 0.9914042 , ..., 1.2498999 , 1.4811479 ,
        1.5482244 ],
       [0.48149085, 0.9309551 , 1.0346954 , ..., 1.1451317 , 1.2529398 ,
        0.8480356 ],
       [0.32020453, 1.0256895 , 0.8800953 , ..., 0.91717625, 1.1567417 ,
        1.0169367 ]], dtype=float32)>

In [102]:
#5
tf.matmul( tf.reshape(rand_T1,(300, 5)), rand_T2)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0.79179823, 1.2873926 , 1.3331751 , ..., 1.0512865 , 1.6138301 ,
        1.6236662 ],
       [0.74643576, 1.3257545 , 1.3729734 , ..., 1.6260417 , 1.8204834 ,
        1.299829  ],
       [1.2140024 , 1.9483186 , 2.3025646 , ..., 1.8813194 , 2.4656518 ,
        2.2417052 ],
       ...,
       [0.95453644, 1.912196  , 1.995398  , ..., 1.8796577 , 2.3959305 ,
        2.017756  ],
       [0.53968245, 1.6568501 , 1.2094977 , ..., 1.6138779 , 1.8913611 ,
        1.6747141 ],
       [0.5335051 , 1.1919428 , 1.0190009 , ..., 1.6569375 , 1.6745753 ,
        0.98854077]], dtype=float32)>

In [107]:
#5
tf.tensordot( tf.reshape(rand_T1,(300, 5)), rand_T2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0.79179823, 1.2873926 , 1.3331751 , ..., 1.0512865 , 1.6138301 ,
        1.6236662 ],
       [0.74643576, 1.3257545 , 1.3729734 , ..., 1.6260417 , 1.8204834 ,
        1.299829  ],
       [1.2140024 , 1.9483186 , 2.3025646 , ..., 1.8813194 , 2.4656518 ,
        2.2417052 ],
       ...,
       [0.95453644, 1.912196  , 1.995398  , ..., 1.8796577 , 2.3959305 ,
        2.017756  ],
       [0.53968245, 1.6568501 , 1.2094977 , ..., 1.6138779 , 1.8913611 ,
        1.6747141 ],
       [0.5335051 , 1.1919428 , 1.0190009 , ..., 1.6569375 , 1.6745753 ,
        0.98854077]], dtype=float32)>

In [109]:
#6
img_tensor = tf.random.uniform((224, 224, 3), 0, 1)
img_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.5749372 , 0.19900596, 0.7038239 ],
        [0.05541027, 0.5884645 , 0.5430788 ],
        [0.9185413 , 0.37144518, 0.84554374],
        ...,
        [0.6570301 , 0.7645861 , 0.48230588],
        [0.41497958, 0.4241538 , 0.5199896 ],
        [0.59315014, 0.23632371, 0.15606153]],

       [[0.34459436, 0.24155474, 0.8630327 ],
        [0.92559505, 0.41881108, 0.9492458 ],
        [0.21597803, 0.15805602, 0.9682605 ],
        ...,
        [0.45298254, 0.6097312 , 0.45232892],
        [0.04503286, 0.48371267, 0.7752477 ],
        [0.644374  , 0.65862846, 0.11632323]],

       [[0.18631506, 0.29340136, 0.3898226 ],
        [0.8457128 , 0.86194694, 0.05938876],
        [0.22856331, 0.74509835, 0.32373703],
        ...,
        [0.03299081, 0.8350847 , 0.77849007],
        [0.5707276 , 0.7097032 , 0.07139933],
        [0.6495327 , 0.17728817, 0.2139225 ]],

       ...,

       [[0.79031277, 0.3867849 , 0.21375918],
        [0.25

In [113]:
#7
minval = tf.reduce_min(img_tensor)
maxval = tf.reduce_max(img_tensor)
minval, maxval

(<tf.Tensor: shape=(), dtype=float32, numpy=2.503395e-06>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9999962>)

In [117]:
#8
rand_T3 = tf.constant(np.random.randint(-128, 127 , [1, 224, 224, 3]))
# rand_T3
tf.squeeze(rand_T3)

<tf.Tensor: shape=(224, 224, 3), dtype=int64, numpy=
array([[[  22,    8,   20],
        [ -80,  -23,   24],
        [  82,  -98,   76],
        ...,
        [ -47,   10,   17],
        [ -27,   41,    0],
        [ 102, -123, -122]],

       [[  31,   81, -110],
        [ -75,   89,   53],
        [-109, -118,   27],
        ...,
        [ -17,   94,  112],
        [ -95,  -29,  -68],
        [-121,    4,  -76]],

       [[ -99,  -85,  114],
        [ -83,  -20,   40],
        [ 100,   74,   62],
        ...,
        [  64,  -15,   65],
        [  -4,  123,   16],
        [ -61,   11,   75]],

       ...,

       [[ -66,  107,  100],
        [  -5,  -54,  -45],
        [ -49,   21,   72],
        ...,
        [  67,  -82,  -42],
        [ -48, -127,   23],
        [  45,  -55, -105]],

       [[ -46,   81,   10],
        [ -62,  -87,  -70],
        [  60,   38,  -40],
        ...,
        [ 110,   52,   23],
        [ -50,  -60,   28],
        [  59,   35,  -70]],

       [[  66,    7

In [131]:
#9
T4 = tf.constant( tf.cast ( np.random.randint(-10, 10, [10]), dtype=tf.float32))

T4.numpy().astype(np.int32), tf.argmin(T4) , tf.argmax(T4)

(array([  8, -10,   5,   6, -10,  -7,   8,  -7,   5,  -4], dtype=int32),
 <tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>)

In [140]:
#10 NOte: onehot(used to convert categorical data to numbers) doesnot work on negative values.
tf.one_hot(T4.numpy(), depth=np.size(T4))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>